### ISSUE TITLE
Missing tar file

### ISSUE THREAD

**Issue by shadowlips** [russianhun/lazyadmin#35]
Hi, there should have been a tar file called files-v2.1.tar.gz, but I don't see any after downloading.  is it correct?

**Comment by russianhun** [comment]
Hey @shadowlips,

Sorry about replying just now, I have all but abandoned github, and this one project forgot to move to Gitlab with me.

The missing tar file should be in the installable release version, portable ones don't have it (since portable means no install). In the main repo, there are only the source files, so if you need a release, go to:

[https://github.com/russianhun/lazyadmin/releases/tag/v2.1](https://github.com/russianhun/lazyadmin/releases/tag/v2.1)

this should be the "latest" one 8although that's not quite fresh either, but I have seen no need for updates since.

I do hope you find LAdmin as useful as it's intended to be. :)

(I'll close this for now, unless you **strongly** disagree.)
